name: FSDFM 
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - matplotlib
  - jupyter
  - numpy
  - pip
  - tqdm
  - pip:
    - pre-commit
    - black==22.6.0
    - usort==1.0.4
    - ufmt==2.3.0
    - flake8==7.0.0
    - ipykernel
    - torchdiffeq
    - scikit-learn
    - pydoclint
    - coverage
    - setuptools_scm
    - setuptools>=77.0.0
    - hydra-core
    - hydra-submitit-launcher
    - datasets
    - transformers
    - wandb
    - einops
    - flow_matching
